### ISSUE TITLE
Any chance to get this working with DHT22/AM2302?

### ISSUE THREAD

**Issue by ThumbGen** [porrey/dht#1]
Hi

Just got a AM2302 sensor and immediately tried your lib/sample. Unfortunately it does not work, I get absolutely no reading at all :(
The Microsoft Sample (OneWire) doesn't work either. To be sure the sensor is not faulty I tried in Raspbian using some Python lib and it works well.

Any chance to get the lib working with that sensor?

TIA

**Comment by porrey** [comment]
I ordered a DHT22 but haven't received it yet. As soon as I get it I will update the library. Please check back at https://www.hackster.io/porrey/dht11 for an update. I'll try to remember to post back here too.

**Comment by porrey** [comment]
I received my DHT22 and was able to get a reading from the library, however, the reading was converted improperly. I updated the library to include a new DHT22 class that has been tested. I did notice that sometimes the DHT22 would not return a reading for a long period of time and required a "reset" (unhook the power). It appears to be more sensitive to the timing than the DHT11. I was able to get it to work consistently though. I used the resistor across the S and V+ inputs as well as a 100nF ceramic capacitor across V+ and GND. I don't think they are completely necessary but are recommended by the datasheets.

**Comment by ThumbGen** [comment]
Great news! Can you please check the solution? It seems some files are missing (dht22.cpp)... 
TIA

**Comment by porrey** [comment]
The file is there now...

**Comment by ThumbGen** [comment]
Unfortunately it does not work with my AM2302 (no readings at all). 

Maybe it worth comparing the code with https://github.com/adafruit/DHT-sensor-library/blob/master/DHT.cpp  (this works perfectly under Raspbian).
For example it seems the AM2302 (maybe DHT22 too?) don't like being queried faster than 2 seconds.

**Comment by porrey** [comment]
The label on my chip is AOSONG AM2302. Everything I read about this chip states that it cannot be read more than once every two seconds. Since the library retries until it gets a reading it violates this. My guess is that trying to take a reading too often triggers something in the chip and causes it to fail. I can get readings from mine most of the time but occasionally it will go 30 seconds without giving a reading.

One minor difference in the Adafruit library is that it waits 20ms instead of 18. Everything else about how this library takes a reading is different because of the lack In ability to control things at a microsecond level.

Try setting retires to 1 and change the timing to every 2 seconds to see if it ever gets a reading. You can tweak the timing from there. I haven't hooked this one up to my Arduino but with he DHT11 I can get a reading every 150ms and it is rated at 1 reading per 2 seconds.

**Comment by zstinnett** [comment]
I also have an AOSONG AM2302, and I tried changing the readings to 2 seconds and the retries to 1 and still do not have any readings. Any other suggestions? Thanks for the help with this!

**Comment by zstinnett** [comment]
So I was actually able to get my Pi to work with my AOSONG A2302 by removing the resistor (4.7K) using only a 100nf capacitor. Also my Pi was running build 10240.0 I updated it to 10556.0 Now I'm averaging a rate of 4.24 seconds.

**Comment by porrey** [comment]
Glad to hear. Hope this solves your problem and gets your project up and running.

If your interested in another approach, I am about to post an article that shows how to connect a Raspberry Pi to an Arduino using the I2C bus and a library I have in GitHub. One of the example sketches uses the DHT22 on the Arduino, but the calls are made from C# on the Raspberry Pi. The article is currently private but will be available soon (waiting for a response from Hackster.io because the publish button is not working).

https://www.hackster.io/porrey/bridging-the-raspberry-pi-and-the-arduino

**Comment by ThumbGen** [comment]
I just wanted to confirm that after updating the raspi to 10556 I am able to read values (without any modification in the code) :)
(I assume removing the resistor is not needed)
8% successful readings with a rate of 12 seconds/reading

Thank you for the lib!

**Comment by zstinnett** [comment]
With out the resistor. Using only a 100nf capacitor. I've been running it for 27 hours have average rate of 2.43 seconds. With a succes rate of 42.2%. Try removing the resistor and see if that helps you.

**Comment by porrey** [comment]
Thanks. I tried it, it improved but the fastest I could get was around 1 reading every 6 seconds.
